### PR TITLE
Update 06-working with columns.md - Rename column added

### PR DESCRIPTION
**Pull request by Biostew**
Update 06-working with columns.md - Rename column instructions added (Line 22)

Please delete this line and the text below before submitting your contribution.

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at team@carpentries.org.  

---

### CODE REVIEW

**Comment by ppival** [comment]
Looks good to me!

**Comment by Biostew** [comment]
Hooray! Thank you very much! It is my first pull request for Library Carpentry (and the Carpentries more widely!) I am looking forward to participating! 🙂

Best wishes,

Sarah
________________________________

**Comment by libcce** [comment]
Hi @Biostew thanks so much for doing this!!! We definitely can use the help :) We just added this to the lesson styles, i.e. menu items, so it would be good to see if it aligns with that http://carpentries.github.io/lesson-example/06-style-guide/index.html.

**Comment by libcce** [comment]
Thanks again @Biostew! I'll update your PR per the style above.

**Pull request merged**
