### PR TITLE
Update 03-working-with-data.md

### PR DESCRIPTION
**Pull request by jas58**
replaced 'row' in figure title with 'record' for image 2 of 2 but also need higher quality resolution to zoom in

Suggested by co-instructor Sept 2023.

still looking for how to update the image

### CODE REVIEW

**Comment by jas58** [comment]
Should I make the screen shot after updating to 3.7?  I'm in 3.6 @ostephens

**Comment by jas58** [comment]
leftScreenshot 2023-11-06 143618
recordsScreenshot 2023-11-06 143707

**Comment by jas58** [comment]
Pausing now to see if it all loads correctly.

**Review by ostephens — CHANGES_REQUESTED** [review]
The new images you've added are JPG, but the existing images are PNG format and markdown in the lesson points to the PNG images.

I can't find any specific advice on which image format to use in carpentries lessons and either would work, but PNG seems to be the standard and what we've used elsewhere in the lessons - so can you remove the JPG versions and create PNG versions to replace the existing images?

**Review by ostephens — APPROVED** [review]

**Pull request merged**
