### PR TITLE
Correct date transformation to ISO 8601

### PR DESCRIPTION
**Pull request by katrinleinweber**
See #106. I'm not sure whether the Carpentries style will correctly count through the duplicate `2.` and can't test it right now.

If it doesn't, please feel free to add commits to my branch that merge the two items into a single `2.` line or renumber the entire block, or whatever you find best

### CODE REVIEW

**Comment by katrinleinweber** [comment]
We could also introduce set `month_first` to `false` and thus examplarise the use of a Boolean datatype.

**Comment by katrinleinweber** [comment]
As [mentioned in #41](https://github.com/LibraryCarpentry/lc-open-refine/issues/41#issuecomment-524420271): While preparing to teach this lesson, I made some other, less critical changes than this date-related one (typos, improved some formatting & rephrased some parts). It's over in [TIBHannover/lc-open-refine:proof-read](https://github.com/LibraryCarpentry/lc-open-refine/compare/gh-pages...TIBHannover:proof-read).

Please feel free to start a separate PR from there after this one, or to [cherry-pick](https://www.atlassian.com/git/tutorials/cherry-pick) just the commits you find useful.

**Comment by libcce** [comment]
Thanks @katrinleinweber!

**Comment by katrinleinweber** [comment]
You're welcome & thanks for merging :-)

**Pull request merged**
