### PR TITLE
Update 13-looking-up-data.md

### PR DESCRIPTION
**Pull request by dromito**
Added a note to check the API documentation for rate limits and other data use requirements.

### CODE REVIEW

**Comment by libcce** [comment]
@dromito this looks good to me, thanks! I've found in workshops that it is always something that we have to stress, the rate limits, before people fetch data from a URL, otherwise they will be waiting for a while and might get kicked off. Should we also include in the note the importance of filtering/choosing a subset of data to work with? Or is that mentioned somewhere else @ostephens ?

**Comment by ostephens** [comment]
@libcce the exercise demonstrates this by using a star facet to select a single row, but it doesn't go further except to say that selecting a single row would be unusual behaviour

**Comment by dromito** [comment]
@ostephens Including the Throttle delay setting and the contact email sounds like a good idea, if it wouldn't be too cumbersome an addition that section.

**Comment by ostephens** [comment]
Given this PR is for a small but useful change, and the additions I've suggested are more work, I'm going to merge this and create a separate issue for the other additions - these will make good first issues

**Pull request merged**
